### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by spj-uk** [davidegironi/minihtmltextbox#1]
I am using the component in a project but finding it is having an issue on a particular machine. "Works on my machine!". DLL is on the client machine

Has anyone else had this problem?

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at DG.MiniHTMLTextBox.MiniHTMLTextBox.timerUpdate_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by davidegironi** [comment]
Hello @spj-uk 
By requirements MSHTML.dll and MS Internet Explorer must be running on the machine.
Have you got client machine specs? O.S. - NET version
Are you running it on .NET or Framework?

**Comment by spj-uk** [comment]
.net 4.8 I have multiple forms using the control. Oddly one windows form does not load on a client machine but others do on the same machine.

**Comment by davidegironi** [comment]
So I think it's related to a problem on that specific Form.
What I can suggest you is to include just fo debugging the code of this library and to check using the Debug compiled version. You should have much more information.
Also get a more comprehensive stacktrace if you can.
