### ISSUE TITLE
The text isn't rendering correctly in the textbox.

### ISSUE THREAD

**Issue by JimWilcox3** [davidegironi/minihtmltextbox#2]
I am using this HTML Textbox to allow users to write the body of an email.  When the email is sent, there are extra linespaces in body of the email that do not show up in the textbox.  Is there a way to make the textbox display exactly what will be rendered in an email body?

Thanks,
Jim

**Comment by davidegironi** [comment]
Hello @JimWilcox3,
can you make a screenshot of what you seen on the component, and what is in the email, and also add the HTML text from textbox and email source?
